# Generated by Django 4.2.7 on 2023-11-28 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z]*$')])),
                ('lastName', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters are allowed.', regex='^[A-Za-z]*$')])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.PositiveIntegerField(max_length=10, unique=True)),
                ('customer_id', models.PositiveIntegerField(max_length=15, unique=True)),
            ],
        ),
    ]
